### ISSUE TITLE
Unable to run test suite successfully due to missing gemfile.lock files

### ISSUE THREAD

**Issue by natebird** [rubymem/bundler-leak#17]
I downloaded the repository fresh and changed to the `fix-dev-environment` branch to avoid the issues described in #12.

Then I ran the following commands:

`bundle install`
`git submodule update --init --recursive`
`bundle exec rspec`

The following tests failed:

```
Failures:

  1) CLI when auditing a bundle with unpatched gems should print a warning
     Failure/Error: expect(subject).to include("Leaks found!")
     
       expected "/Users/nate/code/bundler-leak/lib/bundler/plumber/scanner.rb:61:in `read': No such file or directory...bin/bundler-leak:3:in `load'\n\tfrom /Users/nate/code/bundler-leak/bin/bundler-leak:3:in `<main>'\n" to include "Leaks found!"
       Diff:
       @@ -1,2 +1,12 @@
       -Leaks found!
       +/Users/nate/code/bundler-leak/lib/bundler/plumber/scanner.rb:61:in `read': No such file or directory @ rb_sysopen - /Users/nate/code/bundler-leak/spec/bundle/unpatched_gems/Gemfile.lock (Errno::ENOENT)
       +	from /Users/nate/code/bundler-leak/lib/bundler/plumber/scanner.rb:61:in `initialize'
       +	from /Users/nate/code/bundler-leak/lib/bundler/plumber/cli.rb:41:in `new'
       +	from /Users/nate/code/bundler-leak/lib/bundler/plumber/cli.rb:41:in `check'
       +	from /Users/nate/.gem/ruby/2.6.2/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
       +	from /Users/nate/.gem/ruby/2.6.2/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
       +	from /Users/nate/.gem/ruby/2.6.2/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
       +	from /Users/nate/.gem/ruby/2.6.2/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
       +	from /Users/nate/code/bundler-leak/bin/bundle-leak:10:in `<top (required)>'
       +	from /Users/nate/code/bundler-leak/bin/bundler-leak:3:in `load'
       +	from /Users/nate/code/bundler-leak/bin/bundler-leak:3:in `<main>'
       
     # ./spec/integration_spec.rb:19:in `block (3 levels) in <top (required)>'

  2) CLI when auditing a bundle with unpatched gems should print advisory information for the vulnerable gems
     Failure/Error: expect(subject).to match(advisory_pattern)
     
       expected "/Users/nate/code/bundler-leak/lib/bundler/plumber/scanner.rb:61:in `read': No such file or directory...bin/bundler-leak:3:in `load'\n\tfrom /Users/nate/code/bundler-leak/bin/bundler-leak:3:in `<main>'\n" to match /(Name: [^\n]+
       Version: \d+.\d+.\d+
       URL: https?:\/\/(www\.)?.+
       Title: [^\n]*?
       Solution: upgrade to (~>|>=) \d+\.\d+\.\d+(\.\d+)?(, (~>|>=) \d+\.\d+\.\d+(\.\d+)?)*[\s\n]*?)/
       Diff:
       @@ -1,6 +1,12 @@
       -/(Name: [^\n]+
       -Version: \d+.\d+.\d+
       -URL: https?:\/\/(www\.)?.+
       -Title: [^\n]*?
       -Solution: upgrade to (~>|>=) \d+\.\d+\.\d+(\.\d+)?(, (~>|>=) \d+\.\d+\.\d+(\.\d+)?)*[\s\n]*?)/
       +/Users/nate/code/bundler-leak/lib/bundler/plumber/scanner.rb:61:in `read': No such file or directory @ rb_sysopen - /Users/nate/code/bundler-leak/spec/bundle/unpatched_gems/Gemfile.lock (Errno::ENOENT)
       +	from /Users/nate/code/bundler-leak/lib/bundler/plumber/scanner.rb:61:in `initialize'
       +	from /Users/nate/code/bundler-leak/lib/bundler/plumber/cli.rb:41:in `new'
       +	from /Users/nate/code/bundler-leak/lib/bundler/plumber/cli.rb:41:in `check'
       +	from /Users/nate/.gem/ruby/2.6.2/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
       +	from /Users/nate/.gem/ruby/2.6.2/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
       +	from /Users/nate/.gem/ruby/2.6.2/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
       +	from /Users/nate/.gem/ruby/2.6.2/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
       +	from /Users/nate/code/bundler-leak/bin/bundle-leak:10:in `<top (required)>'
       +	from /Users/nate/code/bundler-leak/bin/bundler-leak:3:in `load'
       +	from /Users/nate/code/bundler-leak/bin/bundler-leak:3:in `<main>'
       
     # ./spec/integration_spec.rb:29:in `block (3 levels) in <top (required)>'

  3) Bundler::Plumber::Scanner#scan should yield results
     Failure/Error: File.read(File.join(@root,gemfile_lock))
     
     Errno::ENOENT:
       No such file or directory @ rb_sysopen - /Users/nate/code/bundler-leak/spec/bundle/unpatched_gems/Gemfile.lock
     # ./spec/scanner_spec.rb:9:in `new'
     # ./spec/scanner_spec.rb:9:in `block (3 levels) in <top (required)>'
     # ./spec/scanner_spec.rb:14:in `block (3 levels) in <top (required)>'

  4) Bundler::Plumber::Scanner#scan when not called with a block should return an Enumerator
     Failure/Error: File.read(File.join(@root,gemfile_lock))
     
     Errno::ENOENT:
       No such file or directory @ rb_sysopen - /Users/nate/code/bundler-leak/spec/bundle/unpatched_gems/Gemfile.lock
     # ./spec/scanner_spec.rb:9:in `new'
     # ./spec/scanner_spec.rb:9:in `block (3 levels) in <top (required)>'
     # ./spec/scanner_spec.rb:21:in `block (4 levels) in <top (required)>'

  5) Bundler::Plumber::Scanner when auditing a bundle with unpatched gems should match unpatched gems to their advisories
     Failure/Error: File.read(File.join(@root,gemfile_lock))
     
     Errno::ENOENT:
       No such file or directory @ rb_sysopen - /Users/nate/code/bundler-leak/spec/bundle/unpatched_gems/Gemfile.lock
     # ./spec/scanner_spec.rb:29:in `new'
     # ./spec/scanner_spec.rb:29:in `block (3 levels) in <top (required)>'
     # ./spec/scanner_spec.rb:31:in `block (3 levels) in <top (required)>'
     # ./spec/scanner_spec.rb:34:in `block (3 levels) in <top (required)>'

  6) Bundler::Plumber::Scanner when auditing a bundle with unpatched gems when the :ignore option is given should ignore the specified advisories
     Failure/Error: File.read(File.join(@root,gemfile_lock))
     
     Errno::ENOENT:
       No such file or directory @ rb_sysopen - /Users/nate/code/bundler-leak/spec/bundle/unpatched_gems/Gemfile.lock
     # ./spec/scanner_spec.rb:29:in `new'
     # ./spec/scanner_spec.rb:29:in `block (3 levels) in <top (required)>'
     # ./spec/scanner_spec.rb:40:in `block (4 levels) in <top (required)>'
     # ./spec/scanner_spec.rb:43:in `block (4 levels) in <top (required)>'

Finished in 1.25 seconds (files took 0.20536 seconds to load)
44 examples, 6 failures

Failed examples:

rspec ./spec/integration_spec.rb:18 # CLI when auditing a bundle with unpatched gems should print a warning
rspec ./spec/integration_spec.rb:22 # CLI when auditing a bundle with unpatched gems should print advisory information for the vulnerable gems
rspec ./spec/scanner_spec.rb:11 # Bundler::Plumber::Scanner#scan should yield results
rspec ./spec/scanner_spec.rb:20 # Bundler::Plumber::Scanner#scan when not called with a block should return an Enumerator
rspec ./spec/scanner_spec.rb:33 # Bundler::Plumber::Scanner when auditing a bundle with unpatched gems should match unpatched gems to their advisories
rspec ./spec/scanner_spec.rb:42 # Bundler::Plumber::Scanner when auditing a bundle with unpatched gems when the :ignore option is given should ignore the specified advisories
```

**Comment by natebird** [comment]
The test `gemfile.lock` files are not generated and I'm not sure where to get them from.

**Comment by bronzdoc** [comment]
@natebird a quick fix to run the specs successfully is to go to `/Users/nate/code/bundler-leak/spec/bundle/unpatched_gems` and `bundle install`

I'm investigating why the `.lock` is not being generated when running the test. Thanks for the report.

**Comment by bronzdoc** [comment]
@natebird have you run what is specified in the README?

```shell
git submodule update --init 
bundle exec rake
```

**Comment by natebird** [comment]
I ran that at some point but I think it was before switching to the `fix-dev-environment` branch. I just ran `bundle exec rake` and it built the gemfile.lock files and ran the tests successfully. Thanks!
